networks:
  bknet:
    external: true

services:
  iam-postgres:
    image: postgres:16
    container_name: iam-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpass
    volumes:
      - iam-pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped
    networks: [ bknet ]

  iam-keycloak:
    image: quay.io/keycloak/keycloak:26.5.1
    container_name: iam-keycloak
    depends_on:
      iam-postgres:
        condition: service_healthy
    command: ["start-dev", "--import-realm"]
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: iam-postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpass

      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-export:/opt/keycloak/data/import:ro
    restart: unless-stopped
    networks: [ bknet ]

  iam-ad:
    image: nowsci/samba-domain:latest
    container_name: iam-ad
    hostname: dc1
    environment:
      - DOMAIN=EXAMPLE.TEST
      - DOMAINPASS=Admin123!
      - DNSFORWARDER=8.8.8.8
      - INSECURELDAP=true
    volumes:
      - iam-ad-data:/var/lib/samba
    restart: unless-stopped
    privileged: true
    networks: [ bknet ]

  # --- Bürokrati: TIM ---
  tim:
    build: ./TIM
    environment:
      - KEYCLOAK_URL=httpdo://iam-keycloak:8080
    restart: unless-stopped
    networks: [ bknet ]

  # --- Bürokrati: Ruuter ---
  ruuter:
    build: ./Ruuter
    volumes:
      - ./dsl:/DSL
    depends_on:
      - tim
    ports:
      - "5000:8080"
    environment:
      - TIM_URL=http://tim:8085
      - TIM_USERINFO_PATH=/jwt/custom-jwt-userinfo
    restart: unless-stopped
    networks: [ bknet ]

volumes:
  iam-pg-data:
  iam-ad-data:
